- CS118NotesFull.md
This is an addition of my notes for all of the things
> Added full notes document

- cs118/part5.md
> Update the path for Class Hierarchy Diagram

- cs118/part2.md
fixed an error describing what types could be used with switch statements, added an example to demonstrate
> Fix switches

- README.md
- cs118/.combinedMarkdown.md
- cs126/index.md
- cs132/index.md
- cs141/index.md
Added modules and disambiguations
> Edmund goodman

- cs118/part5.md
Only actual changes are within lines 333 to 344
> fixed interfaces error

- cs118/index.md
Im not sure if this is the location you would like, but lemme know if you want somewhere else
> Added flash cards link to line 43,

- cs118/.cribSheetMarkdown.md
Constructors can indeed be used by abstract classes :).
> Update .cribSheetMarkdown.md to include note about constructors for abstract classes.

- cs126/pseudoCodes.md
- pseudo code for CS126 algorithms
> Pseudocodes for CS126

- _CS139/HTML.md
The VSCODE extension gives live feedback on any code written in html in the editor.  We could possibly add this as it may help people in their exam?
> Adding another form of validation

- _CS131/index.md
I've added this link to my revision website which provides over 1000 further maths questions of which some topics (such as matrices and calculus) should be relevant to revising 131
> Add 131 revision website link

- _CS131/part2.md
- _CS131/part3.md
- _CS131/part4.md
CS 131 had a number of broken kinks
> fixed broken links

- _CS126/part12.md
Added binary search, and changed the pseudocode to code blocks where it was not being rendered properly
> Fixed some pseudocode

- _CS126/part11.md
- possibly add this site, It might be quite useful as an aid to understanding the algorithms related to graphs
> Link for DFS visualisation

- index.md
Xournal -> xournal++, they are different pieces of software :pensive:
> changed xournal++ name to be more accurate

- _CS141/type-level-programming.md
Added "Reification", updated "Proxy Types, and also included
a section on additional material to illustrate a point.
> Add notes for type-level-programming.

- _CS141/FAM.md
> fixed typo

- _data/CS260.yml
- _layouts/modhome.html
- modules/CS258/Joes_Notes/index.md
- modules/CS260/Joes_Notes/Bit_Multiplication.md
- modules/CS260/Joes_Notes/Divide_and_Conquer_Closest_Points.md
- modules/CS260/Joes_Notes/Divide_and_Conquer_Merge_Sort.md
- modules/CS260/Joes_Notes/Master_Theorem.md
- modules/CS260/Joes_Notes/index.md
Also pulled over a few notes that got caught up with it all.
> Updated page titles on Module home

- CSRGContributing/CreatingCribSheets.md
- _data/CS260.yml
- modules/CS260/Crib_Sheets/Algorithms_Crib_Sheet.md
- modules/CS260/Crib_Sheets/Definitions_Crib_Sheet.md
Added the pages to be URL viewable.
Not added to the modules page undo last commit to add
https://warwick.guide/modules/CS260/Crib_Sheets/Algorithms_Crib_Sheet.html
https://warwick.guide/modules/CS260/Crib_Sheets/Definitions_Crib_Sheet.html
> Added new md files as html pages

- modules/CS130/General_Crib_Sheet/index.md
It's not much g'vnor but it's honest work
> Fix typos on CS130 crib sheet

- _config.yml
- _data/CS139.yml
- modules/CS139/Primary_Notes/Flask.md
- modules/CS139/Primary_Notes/PHP.md
- modules/CS139/Primary_Notes/Python.md
See [the original request](https://github.com/CSRG-Group/dcs-notes.github.io/pull/171)
> Added notes on Flask and Python
